name: Node.js CI

on:
  push:
    branches: [ master, transformation ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm install shadow-cljs
    - run: shadow-cljs compile test
    - run: shadow-cljs release app
    - run: rm -rf target/npm-build 
    - run: mkdir target/npm-build
    - run: cp mastodon-bot.js target/npm-build/
    - run: cp package.json target/npm-build/
    - run: cp README.md target/npm-build/
    - run: tar -cz -C target/npm-build -f target/npm-build.tgz .
