name: unstable
on:
  push:
    tags: '![0-9]+.[0-9]+.[0-9]+*'

jobs:
  unstable:
    name: unstable
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: test em
      run: | 
        npm install
        npm install -g --save-dev shadow-cljs
        shadow-cljs compile test
